In [1]:
import random
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import torch,torchvision
from torch.nn import *
from tqdm import tqdm
import cv2
from torch.optim import *
# Preproccessing
from sklearn.preprocessing import (
    StandardScaler,
    RobustScaler,
    MinMaxScaler,
    MaxAbsScaler,
    OneHotEncoder,
    Normalizer,
    Binarizer
)
# Decomposition
from sklearn.decomposition import PCA
from sklearn.decomposition import KernelPCA
# Feature Selection
from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import RFECV
from sklearn.feature_selection import SelectFromModel
# Model Eval
from sklearn.compose import make_column_transformer
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score,train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error
# Other
import pickle
import wandb

PROJECT_NAME = 'Netflix-Stock-Price-V3'
device = 'cuda:0'
np.random.seed(21)
random.seed(21)
torch.manual_seed(21)

In [2]:
data = pd.read_csv('./data.csv')

In [3]:
data

Date        Open        High         Low       Close   Adj Close  \
0     2015-12-16  119.800003  123.000000  118.089996  122.639999  122.639999   
1     2015-12-17  123.970001  126.349998  122.419998  122.510002  122.510002   
2     2015-12-18  120.849998  122.190002  117.919998  118.019997  118.019997   
3     2015-12-21  119.510002  119.589996  115.660004  116.629997  116.629997   
4     2015-12-22  117.300003  117.430000  114.860001  116.239998  116.239998   
...          ...         ...         ...         ...         ...         ...   
1002  2019-12-10  296.119995  298.940002  292.019989  293.119995  293.119995   
1003  2019-12-11  294.489990  299.429993  294.200012  298.929993  298.929993   
1004  2019-12-12  295.670013  299.170013  295.059998  298.440002  298.440002   
1005  2019-12-13  298.500000  301.799988  297.250000  298.500000  298.500000   
1006  2019-12-16  300.850006  305.709991  298.630005  304.209991  304.209991   

        Volume  
0     13181000  
1     17284900  
2     17948100  
3     11670000  
4      9689000  
...        ...  
1002  10476100  
1003   5589800  
1004   4766600  
1005   3879700  
1006   4658900  

[1007 rows x 7 columns]

In [4]:
data = data['High']

In [5]:
data = torch.from_numpy(np.array(data.tolist())).to(device).float().view(1,-1)

In [6]:
data

tensor([[123.0000, 126.3500, 122.1900,  ..., 299.1700, 301.8000, 305.7100]],
       device='cuda:0')

In [7]:
data_input = data[:,:-1]
data_target = data[:,1:]

In [8]:
data_input

tensor([[123.0000, 126.3500, 122.1900,  ..., 299.4300, 299.1700, 301.8000]],
       device='cuda:0')

In [9]:
data_target

tensor([[126.3500, 122.1900, 119.5900,  ..., 299.1700, 301.8000, 305.7100]],
       device='cuda:0')

In [10]:
class Model(Module):
    def __init__(self):
        super().__init__()
        self.hidden = 512
        self.lstm1 = LSTMCell(1,self.hidden)
        self.lstm2 = LSTMCell(self.hidden,self.hidden)
        self.linear = Linear(self.hidden,1)
    
    def forward(self,X,future=0):
        preds = []
        batch_size = X.size(0)
        h_t1,c_t1 = torch.zeros(batch_size,self.hidden),torch.zeros(batch_size,self.hidden)
        h_t2,c_t2 = torch.zeros(batch_size,self.hidden),torch.zeros(batch_size,self.hidden)
        for X_batch in X.split(1,dim=1):
            X_batch = X_batch.to(device)
            h_t1,c_t1 = self.lstm1(X_batch,(h_t1,c_t1))
            h_t2,c_t2 = self.lstm2(h_t1,(h_t2,c_t2))
            pred = self.linear(h_t2)
            preds.append(pred)
        for _ in range(future):
            X_batch = X_batch.to(device)
            h_t1,c_t1 = self.lstm1(X_batch,(h_t1,c_t1))
            h_t2,c_t2 = self.lstm2(h_t1,(h_t2,c_t2))
            pred = self.linear(h_t2)
            preds.append(pred)
        preds = torch.cat(preds,dim=1)
        return preds

In [11]:
model = Model().to(device)
criterion = MSELoss()
optimizer = Adam(model.parameters(),lr=0.001)
epochs = 100

In [ ]:
wandb.init(project=PROJECT_NAME,name='baseline')
for _ in tqdm(range(epochs)):
    def closure():
        optimizer.zero_grad()
        preds = model(data_input)
        loss = criterion(preds,data_target)
        loss.backward()
        wandb.log({'Loss':loss.item()})
        return loss
    optimizer.step(closure)
    with torch.no_grad():
        future = 100
        n = data_target.shape[1]
        preds = model(data_input,future)
        loss = criterion(preds[:,:-future],data_target)
        wandb.log({'Val Loss':loss.item()})
        preds = preds[0].view(-1).cpu().detach().numpy()
        plt.figure(figsize=(12,6))
        plt.plot(np.arange(n),data_input.view(-1).cpu().detach().numpy())
        plt.plot(np.arange(n,n+future),preds[n:])
        plt.savefig('./img.png')
        plt.close()
        wandb.log({'Img':wandb.Image(cv2.imread('./img.png'))})
wandb.finish()

wandb: Currently logged in as: ranuga-d (use `wandb login --relogin` to force relogin)
wandb: wandb version 0.12.4 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade


In [ ]:
torch.save(data,'./data.pt')
torch.save(data,'./data.pth')
torch.save(data_input,'data_input.pt')
torch.save(data_input,'data_input.pth')
torch.save(data_target,'data_target.pt')
torch.save(data_target,'data_target.pth')